version: '3.8'

services:
  app:
    build: .
    container_name: 2brain-light-app
    restart: always
    env_file:
      - .env
    volumes:
      - ./inputs:/app/inputs
      - ./archive:/app/archive
      - ./credentials.json:/app/credentials.json
      - ./token.json:/app/token.json
    depends_on:
      - db
    networks:
      - 2brain-network

  db:
    image: postgres:15-alpine
    container_name: 2brain-light-db
    restart: always
    environment:
      POSTGRES_USER: ${DB_USER:-user}
      POSTGRES_PASSWORD: ${DB_PASS:-password}
      POSTGRES_DB: ${DB_NAME:-db}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
      - 2brain-network

volumes:
  postgres_data:

networks:
  2brain-network:
